exports.seed = knex =>
  knex('car_filters')
    .del()
    .then(() =>
      knex('car_filters').insert([
        {
          start_year: 1990,
          end_year: 2010,
          gender: 'male',
          countries: [
            'China',
            'South Africa',
            'france',
            'Mexico',
            'Japan',
            'Estonia',
            'Colombia',
            'China',
          ],
          colors: [
            'Green',
            'Violet',
            'Yellow',
            'Blue',
            'Teal',
            'Maroon',
            'Red',
            'Aquamarine',
            'Orange',
            'Mauv',
          ],
        },
        {
          start_year: 1990,
          end_year: 2010,
          gender: '',
          countries: [
            'China',
            'South Africa',
            'france',
            'Mexico',
            'Japan',
            'Estonia',
            'Colombia',
            'China',
          ],
          colors: [
            'Green',
            'Violet',
            'Yellow',
            'Blue',
            'Teal',
            'Maroon',
            'Red',
            'Aquamarine',
            'Orange',
            'Mauv',
          ],
        },
        {
          start_year: 1980,
          end_year: 2002,
          gender: 'female',
          countries: [],
          colors: [
            'Green',
            'Violet',
            'Yellow',
            'Blue',
            'Teal',
            'Maroon',
            'Red',
            'Aquamarine',
            'Orange',
            'Mauv',
          ],
        },
        {
          start_year: 1990,
          end_year: 2000,
          gender: '',
          countries: [],
          colors: [],
        },
        {
          start_year: 1990,
          end_year: 2009,
          gender: '',
          countries: [
            'China',
            'South Africa',
            'france',
            'Mexico',
            'Japan',
            'Estonia',
            'Colombia',
            'China',
          ],
          colors: [],
        },
      ]),
    );
